language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJEMQXFBWODIUGFWQ
  bucket: zack-react-tic-tac-toe
  skip_cleanup: true
  local_dir: dist
env:
  global:
    secure: sXczm8AiE1T2rX7fCH5ojdV/Z5BxMyiF0wt+q3NLsy4bX3rzzVA8iOi4Shc/RFsGTcVrIWGyxro2zSOdC90dIwrgARVa6jRH2whiSE5n64phXpSRwXn3BjkjB7lRS0DaWd6xGf5fgMbGcA0dovPJIi846xKNG6VHrfes/espNABTZpKVFQ3uZA7S/VccybbVMK14PJdrvTaEDrWnlU2kOdwTo2q3juKS3hs6nVPum75T3iug3dPIAwfjcpPEDbdqTigSOfzgopfj+U+SZ+Ioh319sORyCKc/UWCdJEmDYVSXvSpXOn6lEObmNeXwEe7NgOlFm4F1sjQtq2gUwEdyNBbHzQKKsZGDtCrWPNLywjyhg7cSiR+VGk/jtyrgyDKzRlnCklCA8+Au4qsBT/6QkMHl9reo4jYTRlooWf0l4r2GCqwkkPyUPRE1cIzTtWb8h9cfDGphh8S/dSDZiKCV+4+2mb+RuvcY4DjuU1GRXwO/7JKl47NNswwEls74N5MHwf+RUvb1/MhBQArjU3Ex6YuYrWMoRwzteFpnKgG3osJWsA38Fq6NAr9Wn9zhSSKf2wQILznEPlk93l7AVSNS1e0Q8uWHlF/bVpcv906ZeFEHrgpf837C0M3v8XaTlTJFjC24wO+gJ+pgUuqZ6gBwbcxIZA/YJ8oxved1nj7Zamo=
