language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: zack-react-tic-tac-toe
    skip_cleanup: true
    region: us-west-2
    local-dir: dist
    acl: public_read
    on:
      repo: ZackWard/react-tic-tac-toe
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: tictacreact.zackward.net
    skip_cleanup: true
    region: us-west-2
    local-dir: dist
    acl: public_read
    on: 
      repo: ZackWard/react-tic-tac-toe